### ISSUE TITLE
The slack badge looks small in the readme

### ISSUE THREAD

**Issue by sayantan1413** [TemplateRun/TemplateRun.io#25]
#### Current Behavior

The Slack badge does not match the allignment with the other badges in the ReadMe file

#### Expected Behavior

The Slack badge should match the allignment with the other badges in the ReadMe file

#### Screenshots/Logs

<img width="570" alt="Screenshot 2021-09-03 at 11 34 07 PM" src="https://user-images.githubusercontent.com/64970095/132048500-aa54b684-b132-44e9-9f0b-067182b77106.png">

#### Environment

- **Host OS:** Mac Linux Windows
- **Browser**: Chrome Safari Firefox

---

**Comment by debjani1413** [comment]
Done !
