### ISSUE TITLE
[CI] GitHub Action to send notification to Slack when project is starred

### ISSUE THREAD

**Issue by sayantan1413** [TemplateRun/TemplateRun.io#26]
#### Current Behavior

Whenever someone stars our repo we do not receive a notification in our slack channel

#### Desired Behavior

Whenever someone stars our repo we should receive a notification in our slack channel

#### Implementation

A github workflow is needed whenever someone  stars the repo we should receive a notification in our slack channel (#buzz)

#### Acceptance Tests

---

**Comment by debjani1413** [comment]
Done already
