### ISSUE TITLE
[UI]Logo not visible in navbar and footer

### ISSUE THREAD

**Issue by sayantan1413** [TemplateRun/TemplateRun.io#44]
#### Current Behavior

Logo not visible in navbar and footer

#### Desired Behavior

Logo should be visible in the navbar and footer

#### Screenshots/Logs

<img width="130" alt="Screenshot 2021-09-13 at 11 31 40 PM" src="https://user-images.githubusercontent.com/64970095/133133963-33d2f5db-d6c1-4dcb-bacb-d4371518aba9.png">

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows

---

#### Contributor Resources

- 🎨 Wireframes and designs for TemplateRun UI in [Figma](https://www.figma.com/file/lX9Vx4Wax9tDDSPtuUH76w/TemplateRun-site?node-id=312%3A2)

**Comment by warunicorn19** [comment]
@sayantan1413 this is some issue with github pages

**Comment by warunicorn19** [comment]
we havent been able to figure it out

**Comment by sayantan1413** [comment]
Solved!
